# Generated by Django 5.0.2 on 2024-03-25 13:08

import django.db.models.deletion
import planejamento.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planejamento', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.ForeignKey(blank=True, limit_choices_to=planejamento.models.Categoria.escolhas_categoria, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='salario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salario_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='salario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_salario', to='planejamento.salario', verbose_name='Salário'),
        ),
    ]
