# Generated by Django 5.0.2 on 2024-03-25 13:08

import bancos.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosInstitucionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', stdimage.models.StdImageField(default='dados_institucionais/default.png', force_min_size=False, upload_to=bancos.models.get_file_path, variations={'medium': {'crop': True, 'height': 300, 'width': 300}})),
                ('categoria', models.IntegerField(choices=[(1, 'Tipo de conta'), (2, 'Instituição Financeita'), (3, 'Bandeira do cartão')])),
            ],
            options={
                'verbose_name': 'Dados Institucionais',
                'verbose_name_plural': 'Dados Institucionais',
                'ordering': ('categoria', 'nome'),
            },
        ),
    ]
