# Generated by Django 5.0.2 on 2024-03-25 21:43

import movimentacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', movimentacoes.models.CampoMonetario(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Crédito',
                'ordering': ('cartao', 'data', 'categoria', 'valor'),
            },
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')])),
                ('descricao', models.CharField(max_length=100)),
                ('valor', movimentacoes.models.CampoMonetario(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
            ],
            options={
                'verbose_name': 'Movimentações',
                'verbose_name_plural': 'Movimentações',
                'ordering': ('usuario', 'carteira', 'categoria', 'data', 'tipo_movimentacao', 'valor'),
            },
        ),
    ]
