# Generated by Django 5.0.2 on 2024-03-25 13:08

import django.db.models.deletion
import movimentacoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimentacoes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cartao',
            field=models.ForeignKey(blank=True, limit_choices_to=movimentacoes.models.credito.escolhas_usuario, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cartaocredito', verbose_name='Cartão de Crédito'),
        ),
        migrations.AddField(
            model_name='credito',
            name='categoria',
            field=models.ForeignKey(blank=True, limit_choices_to=movimentacoes.models.credito.escolhas_usuario, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='movimentacoes',
            name='carteira',
            field=models.ForeignKey(blank=True, limit_choices_to=movimentacoes.models.limitar_escolhas, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.carteira', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='movimentacoes',
            name='categoria',
            field=models.ForeignKey(blank=True, limit_choices_to=movimentacoes.models.limitar_escolhas, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='movimentacoes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacao_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
