# Generated by Django 5.0.2 on 2024-03-02 00:25

import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', stdimage.models.StdImageField(default='bancos/default.png', force_min_size=False, upload_to='bancos/', variations={'medium': {'crop': True, 'height': 300, 'width': 300}})),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Banco',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banco', to='usuarios.banco', verbose_name='Banco')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteira',
                'ordering': ('usuario', 'banco'),
            },
        ),
    ]
