# Generated by Django 5.0.2 on 2024-03-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_banco_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
