# Generated by Django 5.0.2 on 2024-03-13 22:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='cor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
