# Generated by Django 5.0.2 on 2024-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_categorias_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='tipo_transacao',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')], default=1),
            preserve_default=False,
        ),
    ]
